<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpecStore.Api" Version="1.0.0" />
    <PackageReference Include="STrain.CQS" Version="3.0.0-rc.2" />
    <PackageReference Include="STrain.Eventing" Version="3.0.0-rc.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpecBoard.Api\SpecBoard.Api.csproj" />
  </ItemGroup>

</Project>
